### ISSUE TITLE
[ X-BOT-MD ] Bad Session File, Please Delete Session and Scan Again.

### ISSUE THREAD

**Issue by RuberDucky** [A-S-W-I-N-S-P-A-R-K-Y/X-BOT-MD#11]
0|X-BOT-MD  | OLD SESSION CLOSED
0|X-BOT-MD  | WRITING SESSION...
0|X-BOT-MD  | Starting...
0|X-BOT-MD  | Connected to Api --  8050
0|X-BOT-MD  | Connecting to MongoDB📊
0|X-BOT-MD  | CHECKING FOR EXTERNAL PLUGINS🧩
0|X-BOT-MD  | NO EXTERNAL PLUGINS INSTALLED🧩
0|X-BOT-MD  | BOT IS connecting
0|X-BOT-MD  | BOT IS close
0|X-BOT-MD  | [ X-BOT-MD ] Bad Session File, Please Delete Session and Scan Again.
PM2         | App [X-BOT-MD:0] exited with code [0] via signal [SIGINT]
PM2         | App [X-BOT-MD:0] starting in -fork mode-
PM2         | App [X-BOT-MD:0] online
0|X-BOT-MD  | OLD SESSION CLOSED
0|X-BOT-MD  | WRITING SESSION...
0|X-BOT-MD  | Starting...
0|X-BOT-MD  | Connected to Api --  8050
0|X-BOT-MD  | Connecting to MongoDB📊
0|X-BOT-MD  | CHECKING FOR EXTERNAL PLUGINS🧩
0|X-BOT-MD  | NO EXTERNAL PLUGINS INSTALLED🧩

**Comment by A-S-W-I-N-S-P-A-R-K-Y** [comment]
Use x bot md v3☠️🫱🏻

**Comment by RuberDucky** [comment]
Link please
